### ISSUE TITLE
Notice JSON_PRESERVE_ZERO_FRACTION on php 50617

### ISSUE THREAD

**Issue by carstomas** [nette/utils#100]
PHP_VERSION_ID = 50617

PHP Notice: Use of undefined constant JSON_PRESERVE_ZERO_FRACTION - assumed 'JSON_PRESERVE_ZERO_FRACTION' in /var/www/www/vendor/nette/utils/src/Utils/Json.php:41

**Comment by dg** [comment]
Are you using PECL JSON-C? Is constant JSON_C_VERSION defined?

**Comment by carstomas** [comment]
value of JSON_C_VERSION is 0.11.99
