### ISSUE TITLE
ArrayHash: Unset of key in foreach at on php7 skip some items

### ISSUE THREAD

**Issue by norbe** [nette/utils#103]
```
$hash = \Nette\Utils\ArrayHash::from([1 => 1, 2=> 2, 3=> 3]);
foreach($hash as $key => $value) {
	unset($hash[$key]);
}
dump($hash);
```
Output is: 
```
Nette\Utils\ArrayHash #3f75
2 => 2
```

I'm not sure, is it bug (in php?) or it's just not supported and I'm using it wrong?

**Comment by dg** [comment]
Oh yeah, people today are so lazy to simplify example and search on bugs.php.net. Ten minutes of work: https://bugs.php.net/bug.php?id=70246. IMHO php bug.

**Comment by JanTvrdik** [comment]
I'm not sure this is a bug – see my [comment on php.net](https://bugs.php.net/bug.php?id=70246#1442688950).

* Calling `unset` advances iterator – seems OK to me, what else could it do? Going backwards is generally not possible (there is no `Iterator::prev`)
* Foreach must respect iterator position and continue from there.

**Comment by dg** [comment]
I do not care.

**Comment by norbe** [comment]
Thanks for quick fix. In future, I will try to search better before I post issue here (I have been used google only and did not found anythink relevant).
