### ISSUE TITLE
Strings::match() sometimes fails on Travis

### ISSUE THREAD

**Issue by fprochazka** [nette/utils#104]
[This call](https://github.com/Kdyby/Doctrine/blob/b8f22dd17389bf8a87ca5e84a86e25fffbea5d49/src/Kdyby/Doctrine/DI/OrmExtension.php#L565)

``` php
Nette\Utils\Strings::match('KdybyTests\Doctrine', '#^[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff\\]*\z#')
```

somehow triggers

```
Fatal error: Unpacking unsupported for calls to functions that take any arguments by reference in /home/travis/build/Kdyby/Doctrine/vendor/nette/utils/src/Utils/Callback.php on line 97
```

which is [this line](https://github.com/nette/utils/blob/cf3bb5e487e57776103828d6b5ad2a446fcdf17d/src/Utils/Callback.php#L97).

[This is](https://github.com/Kdyby/Doctrine/blob/6e24abf7a11721ce4a545b26843c8729847a2612/tests/KdybyTests/Doctrine/proxies-sessions-test/callback-override.php#L98-L106) how I found it https://travis-ci.org/Kdyby/Doctrine/jobs/120452083#L350 (open the `after_failure` dump of `*.log`)

---

Sadly, I have very little idea what exactly causes it, since it only happens on travis and I was unable to reproduce it on localhost to experiment on it. 

Does anybody have any idea why this happens, or how to fix it?
## Update

Seems to be relevant to running processes by PHP. I've needed to [run a script, inside a Nette\Tester test case method](https://github.com/Kdyby/Doctrine/blob/b8f22dd17389bf8a87ca5e84a86e25fffbea5d49/tests/KdybyTests/Doctrine/Extension.phpt#L126-L161). While that worked on localhost, it broke on Travis.

This [little change](https://github.com/Kdyby/Doctrine/commit/b28bedb94a731556b7712cc4473f4ad3c13292ca) fixed it - that means the `Strings::pcre()` is somehow dependent on environment variables.
## Update

While passing the current `$_ENV` to the newly started process fixes it for PHP 5.6 & 7.0, on HHVM it [seems to be a bigger issue](https://travis-ci.org/Kdyby/Doctrine/jobs/120455978).

**Comment by milo** [comment]
From my experiencies, the best you can do with `proc_open()` is to not pass env, just [pass NULL](https://github.com/nette/tester/blob/5c4f5ec69d6894cd92bbeb1a216a63914f798761/src/Runner/Job.php#L94) and just `putenv()`. Time to time, some strange errors happens, CLI or CGI differently.

It is because of some system envs are missing.

**Comment by dg** [comment]
I am unable to find "unsupported for" in source code of PHP 7.0.4. It seems like HHVM bug and HHVM is not supported by Nette.

**Comment by dg** [comment]
@fprochazka @milo Is there any way to solve this?

**Comment by milo** [comment]
I think that Nette\Utils is OK and this is a false positive bug report.
