### ISSUE TITLE
Strings::webalize() returns an empty string on Alpine Linux

### ISSUE THREAD

**Issue by mochja** [nette/utils#109]
I think this is due to musl implementation of iconv.

```
bash-4.3# vendor/bin/tester tests -p php -c /etc/php/php.ini
 _____ ___  ___ _____ ___  ___
|_   _/ __)( __/_   _/ __)| _ )
  |_| \___ /___) |_| \___ |_|_\  v1.7.1

PHP 7.0.6 | php -c '/etc/php/php.ini' | 8 threads

ss...............................sssssss.Fs...............F......................F......F......................F.F......

-- FAILED: Nette\Utils\Json::encode() | tests/Utils/Json.encode().phpt
   Failed: Nette\Utils\JsonException was expected, but none was thrown

   in tests/Utils/Json.encode().phpt(39) Tester\Assert::exception()

-- FAILED: Nette\Object undeclared method. | tests/Utils/Object.undeclaredMethod.phpt
   Failed: Nette\MemberAccessException was expected but got Nette\NotSupportedException (PHP extension GD is not loaded.)

   in tests/Utils/Object.undeclaredMethod.phpt(52) Tester\Assert::exception()

-- FAILED: Nette\SmartObject undeclared method. | tests/Utils/SmartObject.undeclaredMethod.phpt
   Failed: Nette\MemberAccessException was expected but got Nette\NotSupportedException (PHP extension GD is not loaded.)

   in tests/Utils/SmartObject.undeclaredMethod.phpt(54) Tester\Assert::exception()

-- FAILED: Nette\Utils\Strings::chr() | tests/Utils/Strings.chr().phpt
   Exited with error code 255 (expected 0)
   E_NOTICE: iconv(): Wrong charset, conversion from `UTF-32BE' to `UTF-8//IGNORE' is not allowed

   in src/Utils/Strings.php(57)
   in src/Utils/Strings.php(57) iconv()
   in tests/Utils/Strings.chr().phpt(14) Nette\Utils\Strings::chr()

-- FAILED: Nette\Utils\Strings::toAscii() | tests/Utils/Strings.toAscii().phpt
   Exited with error code 255 (expected 0)
   E_NOTICE: iconv(): Wrong charset, conversion from `UTF-8' to `ASCII//TRANSLIT//IGNORE' is not allowed

   in src/Utils/Strings.php(185)
   in src/Utils/Strings.php(185) iconv()
   in tests/Utils/Strings.toAscii().phpt(14) Nette\Utils\Strings::toAscii()

-- FAILED: Nette\Utils\Strings::webalize() | tests/Utils/Strings.webalize().phpt
   Exited with error code 255 (expected 0)
   E_NOTICE: iconv(): Wrong charset, conversion from `UTF-8' to `ASCII//TRANSLIT//IGNORE' is not allowed

   in src/Utils/Strings.php(185)
   in src/Utils/Strings.php(185) iconv()
   in src/Utils/Strings.php(201) Nette\Utils\Strings::toAscii()
   in tests/Utils/Strings.webalize().phpt(14) Nette\Utils\Strings::webalize()


FAILURES! (120 tests, 6 failures, 10 skipped, 1.1 seconds)
```

**Comment by dg** [comment]
Can you inspect it or try to fix solution?

**Comment by mochja** [comment]
There is [no transliteration support.](http://www.etalabs.net/compare_libcs.html
)

![image](https://cloud.githubusercontent.com/assets/1218946/14990177/9fc740d6-115b-11e6-82e4-6119ebffa1ca.png)

**Comment by Majkl578** [comment]
I guess your best luck would be by installing php-intl, will that help?
But I think there should be an exception thrown in this case, when no suitable conversion backend is found.

**Comment by mochja** [comment]
List of all installed modules, including intl

```
[PHP Modules]
bcmath
Core
ctype
curl
date
dom
fileinfo
filter
hash
iconv
intl
json
libsodium
libxml
mbstring
memcached
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib
```

@dg possible solution https://github.com/symfony/polyfill-iconv

**Comment by ludekvesely** [comment]
I think there is not problem in Nette but in Alpine Linux. `symfony/polyfill-iconv` didn't work correctly, I had to modify it: https://github.com/ludekvesely/polyfill-iconv/commit/246a7512cd1d6a69beb7e8953895daaa55bfe499. It's a workaround but it works for me. And I agree that there should be notice/exception thrown in this case.

For me these steps worked:

1) remove (or do not install) iconv
```
apk del php7-iconv
```

2) update composer.json
```
...
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/ludekvesely/polyfill-iconv.git"
    }
],
"require": {
    ...
    "symfony/polyfill-iconv": "dev-fix-ignore-order"
}
...
```

3) install polyfill
```
composer update
```

**Comment by Majkl578** [comment]
Have you [reported](https://github.com/symfony/symfony/issues/new) it to upstream?

**Comment by dg** [comment]
It triggers E_NOTICE so it is IMHO ok, or not?

**Comment by ludekvesely** [comment]
I think E_NOTICE is ok.

**Comment by enumag** [comment]
@dg In my opinion it is not ok. On localhost it works fine for me because I've glibc iconv. However in docker it doesn't. Obviously docker has production settings so nobody knew about the E_NOTICE. In my opinion we should fallback to `iconv('UTF-8', 'ASCII', $s)` or throw an exception if `iconv('UTF-8', 'ASCII//TRANSLIT//IGNORE', $s)` returns an empty string (and the string before calling iconv is non-empty).

**Comment by Majkl578** [comment]
@enumag It's not a Docker issue, it's just an issue with the Alpine image. Use different base image that is not intentionally light and missing essential features.

**Comment by enumag** [comment]
@Majkl578 Well Nette already has some workaround for glibc, there is no reason for it to not have another workaround for musl (which is used in alpine) if such workaround is possible. If it is not possible I'd expect an exception that musl implementation of iconv is not supported instead of just E_NOTICE. Returning completely wrong values with just a notice is a bug in my opinion.

**Comment by Majkl578** [comment]
I've never heard of a thing called _musl_ until now and as far as I know there's barely any Linux distro that uses it. I'd be just fine with calling it _unsupported_ (at least for now).

**Comment by enumag** [comment]
Alpine is used quite often to have docker images small. Even if musl is used by Alpine alone it is enough to introduce some support for it in my opinion.

**Comment by plispe** [comment]
@enumag I found a solutions for this problem with iconv //TRANSLIT and //IGNORE flags. You just build php-iconv extension with GNU libiconv. You can see it in this [Dockerfile](https://gist.github.com/guillemcanal/be3db96d3caa315b4e2b8259cab7d07e). I tried it today with php 7.0.19 and it works like a charm.

**Comment by enumag** [comment]
@plispe Thanks but I'm well aware of that solution. My point is this workaround should not be needed or that should be an exception to let me know there is something wrong. Current solution with silent error is insufficient for a library like Nette.

**Comment by dg** [comment]
@enumag so send PR.

**Comment by fprochazka** [comment]
@dg fyi, having you react and confirm sending a PR won't be a waste of time (and won't be rejected right away because of the idea, not wrong implementation) is really helpful. `</no-sarcasm>`

**Comment by plispe** [comment]
@enumag sure, I understand your argument and I agree, that Nette should throw an exception in this case. With my solution(workaround), you can use //TRANSLITERATE and //IGNORE Iconv flags on alpine linux, but it should not be needed in this case.

**Comment by enumag** [comment]
I tried but unfortunately I don't know what to use instead of `//TRANSLIT` and `//IGNORE` to achieve the same result. Any ideas?
