### ISSUE TITLE
Json: Allow to set PHP predefined constants

### ISSUE THREAD

**Issue by legendik** [nette/utils#114]
Currently, we need to set to `json_encode()` second parameter `JSON_PRESERVE_ZERO_FRACTION` but this is not allowed.

It would be really great if we can put all PHP predefined constants for json from http://php.net/manual/en/json.constants.php

**Comment by dg** [comment]
It is set by default.

**Comment by legendik** [comment]
Thanks, we've had an old version :)

I will let this issue open, because of another predefined constants.

**Comment by JanTvrdik** [comment]
Not allowing using custom constants is intentional.
