### ISSUE TITLE
Nette\Image does not remember input format when creating from source

### ISSUE THREAD

**Issue by adambisek** [nette/utils#117]
When I am creating Nette\Image from file or from string, there is no way to get original format.
Reason is that if source is PNG, it is not good to save it into PNG; and vice versa - it makes huge quality loss.

Could i make an PR please?

**Comment by dg** [comment]
Duplicate to https://github.com/nette/nette/issues/96

**Comment by adambisek** [comment]
Sorry. But it was closed and my question is not about files (only input format), so it's not the same issue.
I think Image object should know about his original format. If don't, you have to pass Image and its format, to save image without quality loss - you have to pass twice as much dependencies. 


`
<?php
$image = Image::fromString($upload->getContents());
$originalFormat = Image::Image::getFormatFromString($upload->getContents());
...
$facade = new Facade();
$facade->saveImage($image, $originalFormat);
`

**Comment by dg** [comment]
Corelation between original format and output format is problematic. If you want no quality loss, use PNG. If you want best compression ratio for photos, use JPG.

**Comment by adambisek** [comment]
Sorry, my fail, that sentence should be:
> Reason is that if source is PNG, it is not good to save it into JPG; and vice versa - it makes huge quality loss (eg. on graphics).

Anyway - if somebody uploads PNG, best way is create PNG thumbnail. And if upload JPG, best thumbnail is also JPG. I can't use PNG everytime, eg. for photos, because that thumbnail will be too big.

I did this workaround, I don't like it, but for illustration - https://gist.github.com/adambisek/9b19d3fdaa89435a0f4531f27e277f6b

**Comment by dg** [comment]
Whether is PNG ideal format for thumbnail created from uploaded PNG is highly debatable.
