### ISSUE TITLE
Addition of some methods to Utils\Strings

### ISSUE THREAD

**Issue by icaine** [nette/utils#118]
@dg i would like to add any of following methods:

`camelize($str)`: `"column_to_property" => "columnToProperty"`
`uncamelize($str, '_')`: `"propertyToColumn" => "property_to_column"`
`pascalize($str)`: `"table_to_class" => "TableToClass"`
`wrap($strOrArr, '|')`: `"some text" => "|some text|"`
`wrap($strOrArr, '{', '}')`: `"some text" => "{some text}"`

I have these implemented in my library so if you approve it, i can create PR.

**Comment by TomasVotruba** [comment]
This looks useful for property <=> column conversion.

Do you have any other use cases?

**Comment by icaine** [comment]
Property <=> column, table <=> class, key <=> class, etc. Useful for various code/export/api generators, mappers/bridges, dynamic class loaders...

**Comment by Majkl578** [comment]
I don't think this has many use cases, maybe only wrap...

**Comment by TomasVotruba** [comment]
Until this is feature in PHP 7, this is really useful for:

- collections
- arrays
- collected services (Command, EventSubscriber, <AnyCollected>Interface)

I would have to use [beberlei/assert](https://github.com/beberlei/assert/blob/1a9a5a7ae6ce46558b98a5aee68b3f2d8aa58f3e/lib/Assert/Assertion.php#L49) now just for this use case.

**Comment by dg** [comment]
camelize and uncamelize are fine, pascalize is not needed (the same as ucfirst + camelize), wrap seems not useful to me.
