### ISSUE TITLE
Validators: support for types int[] and string[]

### ISSUE THREAD

**Issue by JanTvrdik** [nette/utils#119]
How do you feel about supporting either specifically `int[]` and `string[]` (defined as _list_ where all values are of given type)?

Or we can generally support `anything[]`, but I don't think that's necessary.

**Comment by JanTvrdik** [comment]
Alternative approach: add `Validators::isListOfType($value, $type)` or add new optional parameter `$type` to current `isList` method.

**Comment by TomasVotruba** [comment]
Do you have any use real cases for this?

**Comment by JanTvrdik** [comment]
Yes, of couse. For example list of ids in query param.

**Comment by TomasVotruba** [comment]
Could you prepare PR for this?

**Comment by JanTvrdik** [comment]
It's undecided how this should be implemented. The implementation itself is likely trivial.

**Comment by TomasVotruba** [comment]
`Validators::isListOfType($value, $type)` seems much clear to me and describes the intention better.

**Comment by dg** [comment]
And what if it is not a list, but a map?

**Comment by JanTvrdik** [comment]
@dg Then it will return FALSE =)

Would you prefer more general approach, e.g. `array<string, bool>` or `vector<string>`?

**Comment by dg** [comment]
In PHP is more understandable `anything[]` than `array<anything>`
