### ISSUE TITLE
Feature request - Image::getBytesPerPixel

### ISSUE THREAD

**Issue by MasterOfZozo** [nette/utils#126]
It might be useful to have method to check bytes per pixel of image. 
Use case: When user download and re-upload file so quality decreases althought image is already compressed.

**Comment by dg** [comment]
`$im->isTrueColor()` returns whether has 1 byte or 3 (4) bytes per pixel.

**Comment by MasterOfZozo** [comment]
I am sorry. Deletinng this issue.
