### ISSUE TITLE
Validators::isUrl returns FALSE when http auth is included

### ISSUE THREAD

**Issue by skrivy** [nette/utils#128]
- bug report? **yes**
- feature request? **no**
- version: 2.4.3

### Description
Validators::isUrl doesn't allow http auth to be included in the provided url.

### Steps To Reproduce
`dump(\Nette\Utils\Validators::isUrl('http://a:b@localhost'));`

**Current output:**
FALSE

**Expected output:**
TRUE

**Comment by JanTvrdik** [comment]
Such URLs are not supported by IE & Chrome for security reasons, see https://bugs.chromium.org/p/chromium/issues/detail?id=82250#c7 and https://support.microsoft.com/en-us/kb/834489

**Comment by dg** [comment]
It is intentional, use `Validator::isUri()`

**Comment by smuuf** [comment]
AFAIK having credentials in URL [_is_ currently supported](https://bugs.chromium.org/p/chromium/issues/detail?id=123150) in Chrome. *(To be fair - it truly is not in Edge.)*

I found this issue when wanting to validate an URL that has `https://username:password@...` in it.

```php
$this->addText('url', 'File:')
	->addRule($this::URL, 'Wrong URL.'); // This, sadly, does not allow credentials in URL.
```

So I tried this, [as suggested](https://github.com/nette/utils/issues/128#issuecomment-272365491):

```php
$this->addText('url', 'File:')
	->addRule(function($control) {
		return \Nette\Utils\Validators::isUri($control->getValue()); // Works, but...
	}, 'Wrong URL.');
```

Unfortunately `Validator::isUri()` seems to be - on the other hand - **overly benevolent**, as it successfully validates abominations like `god:damn.it&httxpf://foo/y.d@ma/*in.co\f/ba\\\\\//..._n\\/an\/\\as.csv?haha`

*Seems to me that some kind of middle ground should be looked for here.*

Also, the format discussed _is_ supported by PHP itself:

```
echo file_get_contents('http://a:b@localhost'); // Works.
```

I know I *can* write my own validation regex, it's just I'm not entirely convinced that Nette framework *(or this package's `Validators::isUrl()` function that is used by framework's `nette/forms` package, to be precise)* should not support quite commonly used format of URL.

**Comment by JanTvrdik** [comment]
> AFAIK having credentials in URL is currently supported in Chrome

Really? I received the following error
![image](https://user-images.githubusercontent.com/175109/27283978-13630da6-54f7-11e7-953e-187f0bd10feb.png)

Firefox emits a warning
![image](https://user-images.githubusercontent.com/175109/27284011-3934911c-54f7-11e7-8e1e-e1d4010325c2.png)

Edge ignores it as well.

**Comment by smuuf** [comment]
# Chrome `59.0.3071.104`

### Without user/password

Trying just https://httpbin.org/basic-auth/user/passwd for user/password:
    
![teteete](https://user-images.githubusercontent.com/6860713/27287778-1635e4b4-5505-11e7-9522-2f1529459058.gif)

### With user/password

Pasting https://user:passwd@httpbin.org/basic-auth/user/passwd (with HTTP credentials) into Chrome's address bar ***works*** - credentials disappear from the address and the page is displayed.

![esff](https://user-images.githubusercontent.com/6860713/27287822-2d5a5756-5505-11e7-8afd-e2829ffb4fb1.gif)


# Firefox `54.0`

Practically the same in Firefox.

- Accessing some *protected* resource eg. https://user:passwd@httpbin.org/basic-auth/user/passwd
    - The warning **is not shown**.
    - Infobox about the fact that the user is about to use username/password **is shown**.
- Sending credentials to a *non-protected* resource eg. https://user:passwd@httpbin.org/anything
    - The warning **is shown** *(not on Chrome, though)*.

**Comment by dg** [comment]
It does not matter what the browser supports. Simply `isUrl()` checks for simple URL without user / pass.

**Comment by smuuf** [comment]
My intention was not really to argue about *what which* browser supports. :) That was more of a reaction to the original argument against the original issue message.

My intention was to try to argue that even though putting user/pass in URIs _is apparently and truly deprecated_, the deprecation RFC is from 2005 ***(that's 12 years ago)*** and yet it is still something that is being used *(and supported)*.

I was just trying to make a case for it being supported by the `isUrl()` validation method - so one could use `->addRule(\Form::URL, '...')` for validating URLs with user/pass in it. If that is something that wouldn't be even considered, I wouldn't lose much sleep over it. :)

**Comment by dg** [comment]
In usual forms, such as form for adding a comment or form for registering on a forum, you will want a URL without a user/name. Therefore, isUrl() validates this way.

**Comment by Majkl578** [comment]
Generic URL validator should allow basic auth. Arguing with Form behavior and not wanting the credentials inside URLs there is sligtly offtopic here, in nette/utils repo. This issue is about generic Nette\Utils\Validators method, not about Form or FormValidators.

Symfony URL validator allows basic auth: https://github.com/symfony/symfony/blob/32f264f/src/Symfony/Component/Validator/Constraints/UrlValidator.php#L25

**Comment by dg** [comment]
So use Symfony URL validator.
