### ISSUE TITLE
Please remove dontation suggestion

### ISSUE THREAD

**Issue by dereuromark** [nette/utils#138]
I kindly ask you to please consider removing the suggestion ( https://github.com/nette/utils/commit/5155d2aa1f45e6d35a04075e760de9eff30cc1f5 ) regarding donating as this is not a technical suggestion.
Refs https://github.com/composer/composer/issues/6334

**Comment by ondrejmirtes** [comment]
I agree. Nette is installed as part of PHPStan (and PHPStan can possibly be blamed for this obtrusive message by an unknowing person) and I really don't want this message to be shown to anyone that doesn't care which depedencies PHPStan uses.

**Comment by Majkl578** [comment]
Agreed, it's annoying misuse.
@ondrejmirtes Mind to share a link to Seldaek's statement? Would be helpful, thanks.

**Comment by ondrejmirtes** [comment]
It's in the linked issue by @dereuromark: https://github.com/composer/composer/issues/6334

**Comment by dg** [comment]
It is basically advertising and advertising is always a bit intrusive and a little creative, so yes, it is a abuse of technical suggestion (and ansi colors), but this way advertising works.

I didn't realize that it may appear to users of tools which only depends on Nette, so I'll remove it from nette/utils, but I'll leave it in some other libraries.

**Comment by dereuromark** [comment]
Thank you!
