### ISSUE TITLE
PHP 7.2 - Cannot use 'Object' as class name as it is reserved

### ISSUE THREAD

**Issue by martinvenus** [nette/utils#146]
- bug report? yes
- feature request? no
- version: 2.*, dev-master

### Description
 - PHP 7.2 uses "Object" as typehint (https://wiki.php.net/rfc/object-typehint).
 - Tested with docker image "php:7.2.0beta2-fpm".

**Comment by dg** [comment]
Already fixed in 2.4 and master, or not?

**Comment by Scorpio1337** [comment]
Same issue.

Docker image: "php:7.2-rc-apache"

Error showed up after installation "kdyby/translation" and loading extension.

**Comment by martinvenus** [comment]
This is not really Nette issue. We should report this to kdyby/* packages.

**Comment by kucix** [comment]
Same error on this line
https://github.com/nette/utils/blob/master/src/Utils/Object.php#L54

**Comment by fidraj** [comment]
@kucix Use `SmartObject`.

**Comment by dada-amater** [comment]
We also cannot update. To many extensions are using it. Is there any workaround?

**Comment by dg** [comment]
Extensions must be fixed, because use forbidden word. No other way.

**Comment by king192** [comment]
docker完美解决
