### ISSUE TITLE
URL validator with numbers

### ISSUE THREAD

**Issue by igorpocta** [nette/utils#148]
- bug report? yes
- feature request? no
- version: 2.4.8

### Description
I have in our company server with hostname "orion2".
When I use URL validator on hostname "orion2", I get AssertionException. 

Before migration it was http://orion/ and it worked.

### Steps To Reproduce
`Validators::assert('http://orion2/network/', 'url', 'console.url');`
Error:
`Nette\Utils\AssertionException #bfee
message protected => "The console.url expects to be url, string 'http://orion2/network/' given." (73)
string private => ""
code protected => 0
file protected => "C:\webserver\htdocs\network\vendor\nette\utils\src\Utils\Validators.php" (71)
line protected => 90
trace private => array (7)
previous private => null`

**Comment by CZechBoY** [comment]
https://regex101.com/r/RqW7Ur/2
Validators::isUrl should return true

**Comment by dg** [comment]
Can you fix it and send PR?

**Comment by dg** [comment]
closing due to human timeout
