### ISSUE TITLE
Validators::is() doesnt work well with pattern containing pipe character (because of string exploding)

### ISSUE THREAD

**Issue by s4muel** [nette/utils#15]
i added a PR https://github.com/nette/utils/pull/14 that covers the pattern e.g.: 'pattern:(John|Carl) Doe'

because of the "foreach (explode('|', $expected) as $item)..." in the is() validator, the validator explodes the string trying to make alternatives of possibilities, but the pipe in the $expected string represents regex alternative. don't know how to solve it generally, so i made just the update to test.

**Comment by dg** [comment]
This is too hard to fix.
