### ISSUE TITLE
Error with Normalizer

### ISSUE THREAD

**Issue by Lumeriol** [nette/utils#153]
- bug report? yes

- version: latest, commit 6b858f6

### Description
Fatal error: Method Nette\PhpGenerator\ClassType::__toString() must not throw an exception, caught Error: Class 'Normalizer' not found

File: vendor\nette\di\src\DI\PhpGenerator.php

Tested on dev-master Sandbox with PHP 7.2 RC4.

**Comment by Majkl578** [comment]
You don't have ext/intl installed or enabled, thus the _class not found_ error.

**Comment by Lumeriol** [comment]
Yes, it was partially truth. I had ext/intl installed and enabled, but there were missing PHP libraries (6x icu??57.dll) in Windows's path, respectively not visible for Apache server.

Thanks and sorry for notice.
