### ISSUE TITLE
Nette\Utils\Reflection::getParameterDefaultValue does not work with private/protected constants

### ISSUE THREAD

**Issue by matej21** [nette/utils#154]
- bug report? yes
- feature request? no

```
Error: Cannot access protected const Foo::BAR
```

is there any reason why `getDefaultValue` cannot be used directly?

**Comment by dg** [comment]
It is workaround for https://bugs.php.net/bug.php?id=72635

**Comment by matej21** [comment]
I see, maybe we can use `ReflectionClassConstant` instead. It throws ReflectionException when a constant is undefined

**Comment by dg** [comment]
Can you send PR? I never heard of `ReflectionClassConstant`.
