### ISSUE TITLE
Add czech filter '%A'

### ISSUE THREAD

**Issue by phoniq** [nette/utils#158]
- bug report? no
- feature request? yes

### Description
Please add czech filter for write Czech name of Day

`{$objekt->datum|date:'%A'}`

**Comment by f3l1x** [comment]
Hi, do you mean 'Pondeli`, `Utery`, ..., `Nedele`? If it's it I'm not sure I should be part of the package. What about other languages?

**Comment by phoniq** [comment]
Hi, yes i mean Pondeli, Utery, ..., Nedele.

**Comment by milo** [comment]
The `%A` works corretly. Output value depends on locale, so you have to set it:
```php
setlocale(LC_TIME, "Czech_Czech");  # Windows
setlocale(LC_TIME, "cs_CZ.utf8");   # UNIX
echo strftime("%A");'
```
But there is a problem on Windows, output value is always in OS encoding, e.g. Windows-1250.

I would recommend to create own filter.
