### ISSUE TITLE
Cannot use 'Object' as class name as it is reserved search►

### ISSUE THREAD

**Issue by JohnyRicio** [nette/utils#160]
- bug report? yes
- feature request? no
- version: 2.4.8

### Description
utils\src\Utils\Object.php - ClassName **Object** in PHP 7.2.1 is reserved. Please rename it.

### Steps To Reproduce
Clear install nette on Windows with Apache and PHP 7.2.1. Try to run app.

**Comment by northys** [comment]
@JohnyRicio you should use https://github.com/nette/utils/blob/ce424a0987f2ed217de1c52ef76970a950e306be/src/Utils/SmartObject.php

If you don't extend Object it should not fail.

**Comment by milo** [comment]
@JohnyRicio Nette itself does not use `Nette\Object` anymore. Could you past there whole exception stacktrace? Are you using any 3rd part library? Some of them may use it.

**Comment by JohnyRicio** [comment]
Should by good mark it as deprecated and after remove it. This issue was my misunderstanding.
