### ISSUE TITLE
Feature request: Arrays::inArray

### ISSUE THREAD

**Issue by ne0-cz** [nette/utils#163]
PHP's [in_array](http://php.net/manual/en/function.in-array.php) function is unsafe by default - the comparison is made without type checking, so it's prone to unexpected errors (e.g. https://news.ycombinator.com/item?id=9484757).

The implementation would be trivial (using the in-built in_array with negated `$strict` parameter) - I can make a PR. The question is if it's something which makes sense for Nette (it feels to me like automatic escaping based on context in Latte, so it should).

Thanks!

**Comment by janedbal** [comment]
I would recommend you to use [phpstan/phpstan-strict-rules](https://github.com/phpstan/phpstan-strict-rules) which checks if you use these `$strict` parameters.

**Comment by dg** [comment]
I think the benefit of such a feature is too small.
