### ISSUE TITLE
Call to undefined function json_last_error()

### ISSUE THREAD

**Issue by phamwon** [nette/utils#177]
Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/7.0.31
Tracy 2.5.2

### Bug Description
I am having this problem on a shared hosting, I try on localhost the same version then it runs well.

![image](https://user-images.githubusercontent.com/3305093/46066864-aa8b0b00-c19f-11e8-9a80-a89709f03b66.png)

**Comment by milo** [comment]
I would check output of `ini_get('disable_functions')` and if present, complain on hosting.
