### ISSUE TITLE
Tokenizer is not suggestion but a must

### ISSUE THREAD

**Issue by szepeviktor** [nette/utils#187]
`"ext-tokenizer": "to use token_get_all()"`

What are your views on declaring tokenizer in "require"?

**Comment by szepeviktor** [comment]
It is not a built-in extension but in tokenizer.so.

**Comment by ktomk** [comment]
Why is this only in suggest? This package gives fatal errors if the extension is not loaded.

**Comment by f3l1x** [comment]
@ktomk Like I get it, it's only suggested because not all classes need tokenizer.

**Comment by szepeviktor** [comment]
In your project you can add ext-tokenizer as a dependency.

**Comment by ktomk** [comment]
I guess adding it in the project is viable in the case at hand but if this would have taken care in this project, this would have been easier and I'm also a bit curious.

**Comment by dg** [comment]
This is simply not required dependency because you are not required to use Nette\Utils\Reflection::getUseStatements()

**Comment by ktomk** [comment]
Okay, you can add me to the list :)
