### ISSUE TITLE
Unexpected constant error

### ISSUE THREAD

**Issue by biswajit-paul** [nette/utils#189]
Version: latest

### Bug Description
When we run on WordPress:

> Error: PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in vendor/nette/utils/src/Utils/Image.php on line 95

### Steps To Reproduce
~~~php
$path = '../../uploads/2019/04/19132_en_1-2.jpg';
$image1 = \Nette\Utils\Image::fromFile($path);
~~~

Works perfect on local system (Ubuntu 18.04 x64)

**Comment by JanTvrdik** [comment]
nette/utils 3.0.x requires PHP 7.1+, you need to upgrade PHP version on your server or install older version of nette/utils

**Comment by biswajit-paul** [comment]
Thank, mine is 7.0+
