### ISSUE TITLE
PHP Notice:  iconv(): Wrong charset

### ISSUE THREAD

**Issue by JarJak** [nette/utils#191]
Version: 3.0.1
PHP version: 7.3.6

### Bug Description
`PHP Notice:  iconv(): Wrong charset, conversion from 'UTF-8' to 'ASCII//TRANSLIT//IGNORE' is not allowed in 
vendor/nette/utils/src/Utils/Strings.php on line 168`

**Comment by JarJak** [comment]
Ok it happens only on PHP Alpine Docker image, here is the solution: https://github.com/docker-library/php/issues/240#issuecomment-305038173

**Comment by Imunhatep** [comment]
No, not ok.. As musl lib is POSIX complient regarding iconv. Either POSIX must be addressed or nette/utils fixed to work by standards.

**Comment by andypost** [comment]
Better to avoid using `TRANSLIT` mbstring is often more predictable
