### ISSUE TITLE
ToAscii: Some russian texts in Cyrillic (Azbuka) are wrong rewrited

### ISSUE THREAD

**Issue by janbarasek** [nette/utils#203]
Hi,

I can speak Russian language and I noticed that the transcription of Cyrillic (Azbuka) to Ascii is sometimes inaccurate.

For example string:

```
dump(Strings::toAscii('для'));
```

should be `dlja`, but not current `dla`, because char `я` means `ja` (Czech) or `ya` (English).

Sample:

![Snímek obrazovky 2019-10-24 v 16 26 54](https://user-images.githubusercontent.com/4738758/67495437-2abdc180-f67b-11e9-9ee4-3c9a8f2ab3cc.png)

If my suggestion makes sense I can implement better translation with support for whole syllables and special cases.

Thanks.

**Comment by dg** [comment]
Do you have enabled Transliterator https://github.com/nette/utils/blob/c133e18c922dcf3ad07673077d92d92cef25a148/src/Utils/Strings.php#L141 and what implementation of iconv are you using? https://github.com/nette/utils/blob/c133e18c922dcf3ad07673077d92d92cef25a148/src/Utils/Strings.php#L154

**Comment by janbarasek** [comment]
@dg Yes, `Transliterator` was instanced and `ICONV_IMPL` is `libiconv`.

I detected it by:

```php
/**
 * Converts UTF-8 string to ASCII.
 */
public static function toAscii(string $s): string
{
	static $transliterator = null;
	if ($transliterator === null && class_exists('Transliterator', false)) {
		$transliterator = \Transliterator::create('Any-Latin; Latin-ASCII');
	}
	dump(['transliterator' => $transliterator, 'iconv' => ICONV_IMPL]);
```

Dumped:

<img width="380" alt="Snímek obrazovky 2019-10-29 v 17 43 49" src="https://user-images.githubusercontent.com/4738758/67789111-b49ecd80-fa73-11e9-8618-13046f11c499.png">

Thanks.

**Comment by dg** [comment]
Transliterator converts `я` to `â` (according to ISO 9 https://cs.wikipedia.org/wiki/ISO_9) and then `â` to `a`.

Probably solution is to add `strtr` for chars `Я я Ю ю` and maybe some others.

**Comment by janbarasek** [comment]
I think we can use (for Czech language):

```php
[
	'ё' => 'jo',
	'ъ' => '',
	'ы' => 'y',
 	'ь' => '', 
	'э' => 'eh', 
	'ю' => 'ju',
	'я' => 'ja',
]
```

But for correct behavior is very important use target language (which can be loaded from second parameter `string $language = 'en'`).

And table for English:

```php
[
	'ё' => 'jo',
	'ъ' => '',
	'ы' => 'y',
 	'ь' => '', 
	'э' => 'e', 
	'ю' => 'yu',
	'я' => 'ya',
]
```
