### ISSUE TITLE
Nette\Utils\Strings::chr() must be of the type int, string given

### ISSUE THREAD

**Issue by LukasVaculcik** [nette/utils#204]
Function Nette\Utils\Strings::chr() requires value type INTEGER but that seems wrong, because it should accept unicode code and that is not an integer. It should accept string.

**Comment by dg** [comment]
Unicode code point is integer.

**Comment by LukasVaculcik** [comment]
then in documentation is wrong statement, that function chr() accepts string
https://doc.nette.org/en/3.0/strings#toc-encoding
anyway, how do you then proceed when:

`$unicodeString = "0x02C7";
Strings::chr( (int)$unicodeString ); //doesnt work
Strings::chr( intval($unicodeString ); //doesnt work`
