### ISSUE TITLE
Cannot use "parent" when current class scope, in Finder

### ISSUE THREAD

**Issue by peldax** [nette/utils#208]
- Version: v3.0.2
- PHP 7.4

### Bug Description

ErrorException: Cannot use "parent" when current class scope has no parent in `vendor/nette/finder/src/Utils/Finder.php:372` which is caused probably by [PHP 7.4 deprecations](https://wiki.php.net/rfc/covariant-returns-and-contravariant-parameters#backward_incompatible_changes).

**Comment by peldax** [comment]
I am sorry, although Finder is in Utils, it has its own repository. I missed it, closing.

**Comment by dg** [comment]
Did you see nette/finder#11 ?

**Comment by peldax** [comment]
Yes, I noticed that right after... 

I have nette/finder 3.0-RC currently installed and thats why I missed the update.
