### ISSUE TITLE
Wrong PHPDoc for `Strings::replace`

### ISSUE THREAD

**Issue by ddebin** [nette/utils#209]
Version: 3.0.2

### Bug Description

PHPDoc for method `Strings::replace` should allow `array` as type for `$replacement`. Otherwise static analysis tools (such as PHPStan) warns for wrong type if an array is given.

https://github.com/nette/utils/blob/c133e18c922dcf3ad07673077d92d92cef25a148/src/Utils/Strings.php#L473

**Comment by dg** [comment]
As I look at the source code, the array must also be callable. So callable is a sufficient type.

**Comment by ddebin** [comment]
With this test content `<?php \Nette\Utils\Strings::replace('', [], []);`, `phpstan analyze -l 5 test.php` returns folowing error : `Parameter #3 $replacement of static method Nette\Utils\Strings::replace() expects (callable(): mixed)|string|null, array() given.`

**Comment by mabar** [comment]
You can use array syntax `[$object, 'calledMethod']` for callable here, just not any array. If phpstan reports valid callable with array syntax as just array then it's a phpstan issue.

**Comment by ddebin** [comment]
I want to give an array as `$replacement`, as would accept `preg_replace`, not a callable.
Btw, same problem with Psalm. Maybe I'm missing something.

**Comment by mabar** [comment]
I see. So you don't want just phpdoc change, but a code change. In case array is not callable it should call preg_replace instead of throwing exception because array is not sufficient for preg_replace_callback.
https://github.com/nette/utils/blob/master/src/Utils/Strings.php#L478-L480

**Comment by ddebin** [comment]
@mabar As I read your answer, I understand that `Strings::replace` doesn't accept same arguments as `preg_replace` (the case array/array for $pattern/$replacement is not handled).

**Comment by ddebin** [comment]
> I see. So you don't want just phpdoc change, but a code change. In case array is not callable it should call preg_replace instead of throwing exception because array is not sufficient for preg_replace_callback.
> https://github.com/nette/utils/blob/master/src/Utils/Strings.php#L478-L480

Yes, that would be nice :-)

**Comment by dg** [comment]
You can use this: `Strings::replace($str, ['\d' => 'xxx', '\s+' => ' '])` …

**Comment by ddebin** [comment]
Thanks @dg, it works.
Anyway, it would have been a nice addition to let `Strings::replace` behaves like `preg_replace`. 
I've been abused by https://github.com/rectorphp/rector/blob/master/config/set/nette/nette-utils-code-quality.yaml with a wrong replacement.

**Comment by dg** [comment]
Unfortunately, this cannot be done because it is not generally possible to determine when the array is callback and when the it is array of replacements.

[Nette\Safe](https://github.com/nette/safe) could be used as a substitute, but it's not finished yet. `Safe::preg_replace($pattern, $replacement, $subject)` as replacement for `preg_replace($pattern, $replacement, $subject)`.

**Comment by ddebin** [comment]
OK. Thanks guys for your replies.
