### ISSUE TITLE
ext-iconv is missing as requirement

### ISSUE THREAD

**Issue by tomasnorre** [nette/utils#215]
Version: 3.1.1

### Bug Description
I have a PHp 7.2 installed with no `ext-iconv` and this makes the Utils/Strings.php failing.
 
`PHP Warning:  Use of undefined constant ICONV_IMPL - assumed 'ICONV_IMPL' (this will throw an Error in a future version of PHP) in /home/tomasnorre/Projects/typo3/ext-crawler/crawler/.Build/vendor/nette/utils/src/Utils/Strings.php on line 150`

The `ext-iconv` is a part of the suggested packages in composer, but to me it looks more like a hard requirement and not just a suggestion.

The might be reasons for this I don't know, perhaps windows computers.

### Expected Behavior
I would expect the composer install to complain before getting installed if all requirements are not fulfilled.

**Comment by janpecha** [comment]
See https://github.com/nette/utils/issues/151#issuecomment-337069523

**Comment by tomasnorre** [comment]
Hmm.  Don't agree with that argument. 

A functionality is a functionality regardless of how small of and edge case it is that uses another external component.

**Comment by tomasnorre** [comment]
Thanks
