### ISSUE TITLE
Do not force string return type from ITranslator interface

### ISSUE THREAD

**Issue by smuuf** [nette/utils#231]
### Is your feature request related to a problem? Please describe.
Due to the change in `\Nette\Localization\ITranslator`, where `string` return type was added in version `3`, we're no longer able to have easily translatable pieces of HTML in our Latte templates/Nette forms.

### Explain your intentions.
Previously, in Nette 2.4, we were able to return instances of [`\Nette\Utils\Html`](https://github.com/nette/utils/blob/c09937fbb24987b2a41c6022ebe84f4f1b8eec0f/src/Utils/Html.php#L233) _(class which implements the `\Nette\Utils\IHtmlString` interface)_ from our own implementation of `\Nette\Localization\ITranslator`. This is no longer possible as of version `3`, due to the added `string` return type, which disallows the previously working logic.

This, unfortunately, makes the transition to Nette 3 very painful.

A "translatable piece of HTML" can, for example, **be some piece of Markdown rendered into HTML**. _Markdown-markuped text_ is identified by our translator, processed, and then returned as a `\Nette\Utils\Html` object (instead of just `string`) - which is then **not escaped** when placed inside a Latte template.

Minimal example from our current `2.4` translator:

```php
class OurTranslator implements \Nette\Localization\ITranslator {

	private $parsedown;

	// ...

	public function translate($message, $count = null) {
		$translated = gettext($message);
		return $this->processMarkdown(sprintf($translated, ...func_get_args()));
	}

	/**
	 * If the string begins with a magic "md:" prefix, process that string as
	 * if it uses markdown markup. This is opt-in to avoid any potential
	 * vulnerabilities from strings provided by untrusted third-parties.
	 *
	 * @return string|\Nette\Utils\Html
	 */
	protected function processMarkdown(string $message) {

		if (strpos($message, "md:") === 0) {
			$html = new \Nette\Utils\Html;
			return $html->setHtml($this->parsedown->line(substr($message, 3)));
		}

		return $message;

	}

}
```

The translator can simply return a `Html` object and then we don't have to deal with manually escaping/unescaping everything in Latte templates. This is because **the `\Latte\Runtime\Filters\escapeHtmlText` itself supports this**:

https://github.com/nette/latte/blob/bda925b140fe1fbc42b14c3f4f6343b808caf795/src/Latte/Runtime/Filters.php#L45-L50
```php
	public static function escapeHtmlText($s): string
	{
		return $s instanceof HtmlStringable || $s instanceof \Nette\Utils\IHtmlString
			? $s->__toString(true)
			: htmlspecialchars((string) $s, ENT_NOQUOTES | ENT_SUBSTITUTE, 'UTF-8');
	}
```

Now, because of the change of the `ITranslator` interface forcing the `string` return type, **this mechanism can no longer be used.**

Yes, in PHP 8 with union types it might be ok to use union `string|IHtmlString|HtmlStringable` return type for the `translate` method, but since that's not what can be done now, **I'm proposing for the removal of the currently needlessly limiting `string` return type**.

**Comment by her-ur** [comment]
We are in the same situation as @smuuf

**Comment by dg** [comment]
How about this?

```php
interface Translator
{
	/** @param  mixed  ...$parameters */
	function translate(string|Stringable $message, ...$parameters): string|Stringable;
}
```

**Comment by her-ur** [comment]
Looks good 👍

**Comment by dg** [comment]
I think it's not even a BC break.

**Comment by martenb** [comment]
What is correct solution of this phpstan error? It looks like BC for me...

```php
$presenter->flashMessage($presenter->translator->translate('Test'));
```

```
Parameter #1 $message of method Nette\Application\UI\Control::flashMessage() expects 
Nette\HtmlStringable|stdClass|string, string|Stringable given.
```

**Comment by petrparolek** [comment]
I rewite code to `$presenter->flashMessage((string) $presenter->translator->translate('Test'));`  everywhere

**Comment by petrparolek** [comment]
@ondrejmirtes  Could you resolve error in `phpstan/phpstan-nette`?

**Comment by ondrejmirtes** [comment]
@petrparolek I'm not going to read all this. Please open an issue in phpstan-nette with a full description of what you are trying to fix.

**Comment by Rixafy** [comment]
Hi, did you manage to solve those phpstan errors? cc @petrparolek @martenb 

So far I have solved it by injecting translator implementation instead of interface, but it's an extra step to think about when injecting dependencies.

I know it's too late, but for use-cases where Html translation is needed, maybe a better solution would be some (project-level) service like `HtmlTranslator(Translator)` where the translated text via translator is parsed as html, and it will be injected only at the places where it's needed, because now we are passing `string|Stringable` to functions that accepts only `string` and we have to resolve these phpstan errors everywhere.
