### ISSUE TITLE
Default value `null` is not used in Arrays::get() method

### ISSUE THREAD

**Issue by BNTRm** [nette/utils#233]
Hello!

Default parameter `null` is not used in `Arrays::get()` method. If I don't pass the default parameter to the function and the key doesn't exists in array then exception will be thrown. Why isn't `null` returned? If I need the function to return `null` by default I have to pass the third parameter `null`, but my IDE marks this parameter as identical to the default value.
Is this a bug or am I missing something?

Thanks!

**Comment by dg** [comment]
It works as expected *Returns item from array. If it does not exist, it throws an exception, unless a default value is set*
 https://github.com/nette/utils/blob/be6f0157dbb500c90ad0762a32a0681e087a6be3/src/Utils/Arrays.php#L24

**Comment by BNTRm** [comment]
I did not understand what the default value `null` is for, but already understood. This value is needed to give a possibility to pass only two arguments

Thanks!
