### ISSUE TITLE
Strings::toAscii inconsistent "fallback" behavior

### ISSUE THREAD

**Issue by cniry** [nette/utils#234]
Version: 3.1

### Bug Description
Strings::toAscii inconsistent "fallback" behavior causes it to silently break my data under certain circumstances.

Strings::toAscii si trying to use 
a) `Transliterator`
b) `iconv`
c) it try to **"at least remove non-ascii chars"**, which is very ugly fallback

Problematic lines:
https://github.com/nette/utils/blob/v3.1/src/Utils/Strings.php#L191

### Steps To Reproduce
Run it with missing Transliterator and iconv.

### Expected Behavior
It shoud throw notice/exception because it is not able to work correctly. Not do it in the mode "eat my data".

### Possible Solution
It shoud throw notice/exception because it is not able to work correctly. Not do it in the mode "eat my data".

**Comment by dg** [comment]
Fixed in 3.2 35fa4152629406c3e61e96a17c95f54e874cf517
