### ISSUE TITLE
PHP 8: Undefined array key (warning)

### ISSUE THREAD

**Issue by dakujem** [nette/utils#236]
Lib Version: 3.1.2
PHP Version: 8.0 (RC3)

### Bug Description

![image](https://user-images.githubusercontent.com/443067/98667812-3f84fa00-234f-11eb-8af3-a58eeec7ae51.png)

I have not dug deeper to find out what is causing this. Works fine with PHP 7.4.

I suspect the `parseUseStatements` method does not return what is suspected.
Simple `return $cache[$name] ?? [];` ~~seems to solve this.~~ UPDATE: no, this does not solve the issue, the factory is not implemented, even though this method no longer raises the warning.

UPDATE:
This is the code of the interface referenced by the reflection passed to `Nette\DI\Helpers::getReturnType` in the call stack above. Nothing special about it.
```php
namespace App\AdminModule\Components;

interface AdminBreadcrumbsControlFactoryInterface
{
    /**
     * @return AdminBreadcrumbsControl
     */
    public function create();
}
```

**Comment by dg** [comment]
Did you tried 3.1.3?

**Comment by dakujem** [comment]
I'm sorry, it does work with `3.1.3`, my bad. Now I'm getting an error with `DependencyChecker` though.

**Comment by dg** [comment]
nette/di is not ready for PHP 8 yet

**Comment by dakujem** [comment]
Okay, I reported it nevertheless, so it is not missed when the package is updated for php 8. https://github.com/nette/di/issues/249
