### ISSUE TITLE
Nullable $replacement for ::pcre() fails

### ISSUE THREAD

**Issue by dakur** [nette/utils#241]
Version: 3.1.4  
PHP 8.0.0

### Bug Description
Calling `Strings::pcre('preg_replace', ['#\\.#', NULL, '70', -1])` fails with `Fatal error: Uncaught TypeError: preg_replace(): Argument #2 ($replacement) must be of type array|string, null given`

It happens when using `symplify/easy-coding-standard`, but it looks rather like error with PHP 8.0 compatibility in `nette/utils`.

![image](https://user-images.githubusercontent.com/9862581/100428089-bf230080-3093-11eb-91ff-14d3fe22e95c.png)

**Comment by dakur** [comment]
Strange is that I have not found any mentions of `preg_replace` API change.

**Comment by dg** [comment]
`Strings::replace('70', '#\\.#')` - there is missing replacement

**Comment by dakur** [comment]
Yeah, but `Strings::replace()` should throw an exception in such case, shouldn't it?

**Comment by dakur** [comment]
Or maybe just make the argument obligatory..

**Comment by genesiscz** [comment]
Can we get a new version released so this gets fixed?
