### ISSUE TITLE
Exception thrown while running phpstan

### ISSUE THREAD

**Issue by driade** [nette/utils#242]
Version: 2.5.6

### Bug Description
PHP Fatal error:  Uncaught Nette\DI\ServiceCreationException: Method PHPStan\Reflection\FunctionReflectionFactory::create() used in service '24' has not return type hint or annotation @return. in /var/www/arge/src/vendor/nette/di/src/DI/ContainerBuilder.php:419
Stack trace:
#0 /var/www/arge/src/vendor/nette/di/src/DI/ContainerBuilder.php(322): Nette\DI\ContainerBuilder->resolveImplement(Object(Nette\DI\ServiceDefinition), 24)
#1 /var/www/arge/src/vendor/nette/di/src/DI/Compiler.php(249): Nette\DI\ContainerBuilder->prepareClassList()
#2 /var/www/arge/src/vendor/nette/di/src/DI/Compiler.php(177): Nette\DI\Compiler->generateCode()
#3 /var/www/arge/src/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(306): Nette\DI\Compiler->compile()
#4 [internal function]: Nette\Configurator->generateContainer(Object(Nette\DI\Compiler))
#5 /var/www/arge/src/vendor/nette/di/src/DI/ContainerLoader.php(125): call_user_func_array(Array, Array)
#6 /var/www/arge/src/vendor/nette/di/src/DI/ContainerLoader.php(85): Nette\DI\ContainerLoader->generat in /var/www/arge/src/vendor/nette/di/src/DI/ContainerBuilder.php on line 419

The very code that seems to be problem is

```
interface FunctionReflectionFactory
{

    public function create(
        \ReflectionFunction $reflection,
        array $phpDocParameterTypes,
        Type $phpDocReturnType = null
    ): FunctionReflection;

}
```

### Steps To Reproduce
I've got this error in Laravel 5.4 installation, with php 7.0, while trying to run phpstan 0.9.3

### Expected Behavior
Not an exception to be thrown. It's works with 2.5.5

**Comment by driade** [comment]
Thanks in advance.

**Comment by dg** [comment]
Fixed
