### ISSUE TITLE
\Nette\Utils\DateTime::fromParts(2021,12,28) causing crash

### ISSUE THREAD

**Issue by tprochazka** [nette/utils#248]
Nette version: 3.0.8
PHP: 7.2.11 (I did not test the newer version, but Nette has 7.2 as the minimum supported version)
Czech localization system and `setlocale(LC_ALL, 'cs_CZ');`

`\Nette\Utils\DateTime::fromParts(2021,12,28)`

End with this exception:
`DateTime::__construct(): Failed to parse time string (2021-12-28 00:00:0,00000) at position 23 (0): Unexpected character`

I tried to change line
https://github.com/nette/utils/blob/c77ecc38a9e20826a9e08fa478d89a7b6de7d999/src/Utils/DateTime.php#L77
to
`$s = sprintf('%04d-%02d-%02d %02d:%02d:%02d', $year, $month, $day, $hour, $minute, $second);`

And it works now.

Do we need microseconds there, if biggest possible entered value is 1s?

**Comment by milo** [comment]
Probably better fix is usage of %F which is non-locale aware.

**Comment by tprochazka** [comment]
Yes. This will also work.  So it is caused by `,` instead of `.`
But I tested it and adding `.000000` brings no difference in the result.
It anyway ends with
```
Nette\Utils\DateTime
date: '2020-12-28 00:00:00.000000'
timezone_type: 3
timezone: 'Europe/Prague'
```
