### ISSUE TITLE
Strings::webalize() could be a little smarter

### ISSUE THREAD

**Issue by janbarasek** [nette/utils#249]
Hello,

when rewriting the names of articles and other user input on the slug, I come across 2 special cases that `Strings::webalize()` could solve automatically:

- `MyFileName` => `my-file-name`
- `abcd123efgh` => `abcd-123-efgh`

If it makes sense, I'll send PR.

Thanks.

**Comment by mabar** [comment]
> Modifies the UTF-8 string to the form used in the URL

Imho it's out of scope. Also I have a project which webalizes unique alphanumeric codes. This would add a lot of dashes into them and make them invalid.

**Comment by janbarasek** [comment]
@mabar Ok, I understand that. However, the `webalize()` function is often used to create part of a URL (even in the title).

What about a second function (such as `slug()`) that would be a little smarter and implement more clever logic?

**Comment by JanTvrdik** [comment]
None of this proposal are applicable for general input. You don't want `b2b` to be converted  to `b-2-b` and you don't want `GitHub` to be converted to `git-hub`. The current behavior is much better.
