### ISSUE TITLE
Wrong mechanism of detecting ArrayHash::offsetExists()

### ISSUE THREAD

**Issue by zeleznypa** [nette/utils#252]
When i call the following code:
```php
$value = null;
$data = new Nette\Utils\ArrayHash();
$data->offsetSet('foo', $value);
```
I expect  that key `foo` exists, with `NULL` as value, but when I call `offsetExists` I will gain `false`

It will be better IMHO to use the [property_exists](https://www.php.net/manual/en/function.property-exists.php) instead of `isset` [here](https://github.com/nette/utils/blob/0e350ef848fa9586eac0748479ca013e8fab6cbd/src/Utils/ArrayHash.php#L83)

**Comment by dg** [comment]
Do you think `isset($data->foo)` should be different from `isset($data['foo'])`?

**Comment by zeleznypa** [comment]
Good question :)

Unfortunately you can't call `array_key_exists` on `\ArrayAccess` for this case.
I can call the property_exists  on it, but it is based on the current inner implementation of the `ArrayHash`.

So the answer is not 100% "no"...

**Comment by dg** [comment]
I suggest not wasting time and energy on this matter :)

**Comment by zeleznypa** [comment]
I though about possibilities how to do it properly, but also not found the 100% silver bullet solution.

So for my case I have own class that extends the `Nette\Utils\ArrayHash` object and overwrite the method for my case.

```php
    /**
     * offsetExists null value hotfix
     *
    public function offsetExists($key): bool
    {
        return property_exists($this, (string) $key);
    }
```

Thanks for your time David and for your more than good work.
