### ISSUE TITLE
iteration over ArrayHash with reference

### ISSUE THREAD

**Issue by Ciki** [nette/utils#253]
Hi @dg, [this hotfix](https://github.com/nette/utils/issues/103#issuecomment-198329790) breaks iteration over ArrayHash with reference, which is quite unpredictable until one looks into the code..
```php
$hash = \Nette\Utils\ArrayHash::from([1]);
foreach($hash as $k => & $v) {
    $v = 2;
}
dump($hash);
```

result
```php
Nette\Utils\ArrayHash
0: 1
```
I don't know if that can be fixed somehow, but at least it could be mentioned in [doc](https://doc.nette.org/cs/3.1/arrays#toc-arrayhash) for newcomers

**Comment by dg** [comment]
I can't think of a way to fix it, but feel free to add it to the documentation.

**Comment by dg** [comment]
Ping @Ciki
