### ISSUE TITLE
Image::class and JPG compatible file formats

### ISSUE THREAD

**Issue by forgie1** [nette/utils#259]
Version: 3.2.2

### Bug Description
`Image::save('image-file.jfif', 90)`  throws `Nette\InvalidArgumentException`

### Expected Behavior
a) properly save the image, since it is jpg compatible format
b) throw `UnknownImageFileException` not a `InvalidArgumentException`

### Possible Solution
change this row: https://github.com/nette/utils/blob/v3.2.2/src/Utils/Image.php#L566
to: `$extensions = array_flip(self::FORMATS) + ['jpg' => self::JPEG] + ['jfif' => self::JPEG];`
but there are more compatible JPG formats/file extensions supported by browsers: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types not only jpg/jpeg/jfif

**Comment by dg** [comment]
You can use `$image->save('filename.jfif', 90, Image::JPEG)` for not quite common suffixes.
