### ISSUE TITLE
paginator: add methods for first and last record on page

### ISSUE THREAD

**Issue by khorsky** [nette/utils#262]
- Explain your intentions
Add two simple methods to the paginator, that could be useful for the user of the paginator: `firstRecordOnPage`, `lastRecordOnPage`. It would allow to display current record range on page in pagination visualization when needed (eg. "records 20 - 27 of 27").

- It's up to you to make a strong case to convince the project's developers of the merits of this feature
These methods provide quite simple calculations, that are based on data already known in paginator. When one wants to display this in application, it must be calculated all over again. It seems logic to have all the pagination math here.

I would prepare PR in case you found this request beneficial. Otherwise feel free to close it.

**Comment by dg** [comment]
That makes sense. Except it should be called like `getFirstItemOnPage` and `getLastItemOnPage`.
