### ISSUE TITLE
Error ! - ReflectionProperty::getType()

### ISSUE THREAD

**Issue by 24uWEB** [nette/utils#265]
Version: 3.2.4

### Bug Description
Hello ( Ahoj ), 

Today morning I run "composer update" on server where is running my website and when I opened website in browser I get error "ReflectionProperty::getType()". I find out the error is caused by Nette/Utils v3.2.4 ( new version ) because when i manualy update version in composer.json to 3.2.2 or 3.2.3 everything works fine. I'am using php 7.3.

Thank you,
Have a nice day,
Filip

![error](https://user-images.githubusercontent.com/83555955/133968286-4460f0dc-67ac-4f92-b3c9-f19266013174.png)

### Steps To Reproduce
Run command "composer update" on application using Nette ( I have in composer json "nette/utils": "^3.2" )

**Comment by lulco** [comment]
Same issue with 3.1.5 on php < 7.4

**Comment by lulco** [comment]
http://php.netmadeira.com/manual/de/reflectionproperty.gettype.php

ReflectionProperty::getType() is available from php 7.4

**Comment by dg** [comment]
Fixed in 3.1.6 & 3.2.5
