### ISSUE TITLE
Compatibility of Nette/Utils with PHP 8.3.2 - warning is generated by StaticClass

### ISSUE THREAD

**Issue by Marian-Kechlibar** [nette/utils#307]
When running on PHP 8.3.2, classes that use the StaticClass trait will generate warnings:

Private methods cannot be final as they are never overridden by other classes

This appears to be caused by the private final constructor introduced when solving the following previous bug:

https://github.com/nette/di/issues/292

**Comment by JanTvrdik** [comment]
ref https://github.com/php/php-src/issues/13177

**Comment by dg** [comment]
fixed in v4.0.4
