### ISSUE TITLE
Nested HTML elements not working as expected

### ISSUE THREAD

**Issue by m-ober** [nette/utils#309]
Version: 4.0.4

### Bug Description
The example (taken from documentation)
```php
$el = Html::el('ul')
	->create('li', ['class' => 'first'])
		->setText('hello');
// <ul><li class="first">hello</li></ul>
```
is not working es expected.

### Steps To Reproduce
https://fiddle.nette.org/nette/#1ce0434e2a

The output is: `<li class="first">hello</li>`

### Expected Behavior
According to the docs, the output should be `<ul><li class="first">hello</li></ul>`

**Comment by m-ober** [comment]
Thanks for the response - working with the `$ul` variable gives the expected result.

**Comment by dg** [comment]
fixed in documentation
