### ISSUE TITLE
Compile Error - Declaration of Nette\SmartObject::__call

### ISSUE THREAD

**Issue by kropacekt** [nette/utils#315]
Version: 4.0.4

### Bug Description
```
Compile Error: Declaration of Nette\SmartObject::__call(string $name, array $args) must be compatible with Nette\Forms\Controls\BaseControl::__call(string $name, array $args): mixed in /var/www/html/vendor/nette/utils/src/SmartObject.php:28
```

### Steps To Reproduce
Install:
* `nette/utils` **v4.0.4**
* `nette/forms` **v3.2.3**

### Possible Solution
I suggest adding the `mixed` type to `\Nette\SmartObject::__call` or removing it from `\Nette\Forms\Controls\BaseControl::__call`.

Please let me know which solution you prefer, and I will create a pull request. Thank you.

**Comment by mabar** [comment]
Related issue (cz only) - https://forum.nette.org/cs/36492-compile-error-smartobject

**Comment by dg** [comment]
Forms 3.0 are unsupported long time

**Comment by kropacekt** [comment]
> Forms 3.0 are unsupported long time

Sorry, I mentioned the wrong version. This error occurs in the latest version of `nette/forms` **3.2.3**.

**Comment by kropacekt** [comment]
@dg Now you can see?

Please let me know how can I help fix this error, thanks.

**Comment by kropacekt** [comment]
Hi @dg and thanks a lot for fixing this.

Would it be possible to release a new tag that includes this fix?

Thanks in advance!
