### ISSUE TITLE
Unknown named parameter $forceArray

### ISSUE THREAD

**Issue by teamayu** [nette/utils#321]
Version: 4.0.5

As per the docs:
Json::decode('{"variable": true}', forceArray: true); // returns an array

However, it throws an exception:
Unknown named parameter $forceArray

**Comment by teamayu** [comment]
Ah, it's a typo, it should be forceArrays.

**Comment by dg** [comment]
fixed

**Comment by teamayu** [comment]
Thanks Dave.
