### ISSUE TITLE
Element `link` does not proccess properly

### ISSUE THREAD

**Issue by dragomano** [nette/utils#322]
Version: latest

### Bug Description
I want to get the `link` element with the specified link inside, but I am getting an unclosed element.

### Steps To Reproduce
`Html::el('link', 'some url')->toHtml()` // -> `<link>`

### Expected Behavior
`<link>some url</link>`

**Comment by dg** [comment]
It is HTML, not XML.

**Comment by dragomano** [comment]
It's quite strange; why then did all the other tags related to RSS form without any issues? :)

**Comment by dg** [comment]
RSS is XML and HTML is not XML.
