### ISSUE TITLE
Nette\Utils\DateTime::createFromFormat() not compatible with PHP7

### ISSUE THREAD

**Issue by kukulich** [nette/utils#53]
Declaration of Nette\Utils\DateTime::createFromFormat() should be compatible with DateTime::createFromFormat($format, $time, DateTimeZone $object = NULL)

I can prepare pull request, however I'm not sure what solution is right. I think there's maybe only one solution - remove the support for timezone as a string and add \DateTimeZone type hint. Deprecated warning will not work if the next version should have two years support.

**Comment by Majkl578** [comment]
See https://github.com/php/php-src/commit/8e19705a93d785cd1ff8ba3a69699b00169fea47.
This cannot be fixed, your proposal would break 5.x compatibility.

**Comment by kukulich** [comment]
Ah, I see. So I close it now.

**Comment by dg** [comment]
The only way is to deprecate and then remove this method.

**Comment by JanTvrdik** [comment]
> This cannot be fixed

Not true, it can be fixed, only the fix is to nice. You conditionally define class `DateTimeFix` with different `createFromFormat` signatures and let `DateTime` extend this `DateTimeFix`.

**Comment by dg** [comment]
The discussion whether it is the worst kind of BC break or not is awesome :-))
