### ISSUE TITLE
Nette\Utils\DateTime compatible problem in PHP 7

### ISSUE THREAD

**Issue by f3l1x** [nette/utils#60]
Report: 

PHP Strict Standards:  Declaration of `Nette\Utils\DateTime::createFromFormat()` should be compatible with `DateTime::createFromFormat($format, $time, DateTimeZone $object = NULL)` in `vendor/nette/utils/src/Utils/DateTime.php` on line 127

Just for keeping in mind. It is not need to fix it now,

**Comment by JanTvrdik** [comment]
This is a known issue https://github.com/nette/utils/pull/58

**Comment by f3l1x** [comment]
Oh sorry, I didn't see it.

**Comment by JanTvrdik** [comment]
This is the relevant discussion about this issue https://github.com/php/php-src/commit/8e19705a93d785cd1ff8ba3a69699b00169fea47
