### ISSUE TITLE
Exception string: Unsupported image type '$type'.

### ISSUE THREAD

**Issue by JosefRypacek** [nette/utils#71]
Hi,

I've just got weird message, while saving image. It seems like typo.
`throw new Nette\InvalidArgumentException('Unsupported image type \'$type\'.')`

So I would like to fix & pull, but suggested solution is not good enough. When user uploads image "example.jpegg" variable $type is empty and message is: Unsupported image type ''.
`throw new Nette\InvalidArgumentException("Unsupported image type '$type'.");`

Can somebody (with more experience) take this issue? 
Thanks

**Comment by enumag** [comment]
See #72.

**Comment by JosefRypacek** [comment]
Nice. Thanks
