### ISSUE TITLE
addAttributes overrides previous values

### ISSUE THREAD

**Issue by TomasVotruba** [nette/utils#88]
The [`addAtributes` method](https://github.com/nette/utils/blob/0deca02158d88d260db1a45d7c8ed84be5a2bcc1/src/Utils/Html.php#L122) of Html object works morelike as `setAttributes`.

It causes me problems while adding class to form element on multiple places - typically with Bootstrap 3 renderer and my custom class.

```php
$form = new Form;
$form->addText('name', 'Name');
    ->getControlPrototype()->addClass('myClass');

// or in non magic way
$form->addText('name', 'Name');
    ->getControlPrototype()->addAttributes(['class' => 'myClass']);

// this has the same impact, at least with correct **set** naming 
// that implies overriding of former value
$form->setAttribute('class', 'someClass'); 
```

The unit test:

```php
$paragraphElement = Html::el('p');
$paragraphElement->addAttributes(['class' => 'primary']);
$this->assertSame(' class="primary"', $paragraphElement->attributes());

$paragraphElement->addAttributes(['class' => 'secondary']);

// this fails
$this->assertSame(' class="primary secondary"', $paragraphElement->attributes());

// this passes
$this->assertSame(' class="secondary"', $paragraphElement->attributes());
```

Is this intended behavior?

If not, shall I send PR?

**Comment by dg** [comment]
That `addAttributes` overrides previous values is IMHO expected behavior. Conversely, it would not be expected if `addAttributes(['id' => 'newvalue'])` will generate `id="oldvalue newvalue"` etc. I don't know if there is any other attribute (except `class`) where will be useful to append values instead of overwriting them.

**Comment by TomasVotruba** [comment]
How to achieve adding a class then?

**Comment by dg** [comment]
Via `addClass()`?

**Comment by TomasVotruba** [comment]
I used that, but didn't like it's magic method.

I also don't have this issue anymore, so it can be closed.
