### ISSUE TITLE
Nette\Object magic setters ignore "use" section.

### ISSUE THREAD

**Issue by miroslav-mrazek** [nette/utils#98]
```
namespace App\Components;
use App\Model\Data\Person;

/**
 * @method setPerson(Person)
 * @method setPerson(App\Model\Data\Person)
 */
```
- First annotation throws: `Argument passed to App\Components\AssignmentPanel::setPerson() must be App\Components\Person, object given.`.
- Second works fine.

**Comment by dg** [comment]
Yes, it is known limitation and will not be fixed (it is nearly impossible).
